RobinRound.cpp
heyimShivam/Algorithm pull request #90
Opened 2022-10-05 15:10 UTC by Mridul07Sharma

2022-10-05 15:20 UTC, heyimShivam commented
Please indent  the code.

2022-10-05 15:37 UTC, Mridul07Sharma commented
@heyimShivam it is already indented.

2022-10-06 14:28 UTC, heyimShivam requested changes
Please correct indentation in whole file

2022-10-06 14:28 UTC, heyimShivam commented on RobinRound.cpp
> +
no need for new line after comment

2022-10-06 14:28 UTC, heyimShivam commented on RobinRound.cpp
> +
no need

2022-10-06 14:28 UTC, heyimShivam commented on RobinRound.cpp
> +
no need of blank line

2022-10-06 14:28 UTC, heyimShivam commented on RobinRound.cpp
> +
no need of blank line

2022-10-06 14:28 UTC, heyimShivam commented on RobinRound.cpp
> +        for (int i = 0 ; i < n; i++)
no need of blank line

2022-10-06 14:28 UTC, heyimShivam commented on RobinRound.cpp
> +                done = false; // There is a pending process
``
```suggestion
            if (rem_bt[i] > 0) { 
                done = false; // There is a pending process 
```

2022-10-06 14:28 UTC, heyimShivam commented on RobinRound.cpp
> +                // quantum. Last cycle for this process
```suggestion
                if (rem_bt[i] > quantum) { 
                    // Increase the value of t i.e. shows 
                    // how much time a process has been processed 
                    t += quantum; 
                    // Decrease the burst_time of current process 
                    // by quantum 
                    rem_bt[i] -= quantum; 
                } 
                // If burst time is smaller than or equal to 
                // quantum. Last cycle for this process 
```

2022-10-06 14:42 UTC, Mridul07Sharma reviewed
Changes done

2022-10-07 06:51 UTC, heyimShivam approved these changes
LGTM, Thanks for the changes

2022-10-07 06:51 UTC, merged